# примеры API-запросов


# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json


###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 22ade1c9e2fbd003dd07d044c6e48a3a083cff42

{
  "title": "IKEA",
  "description": "Срочно"
}


###

DELETE {{baseUrl}}/advertisements/14/
Authorization: Token  22ade1c9e2fbd003dd07d044c6e48a3a083cff42

###
# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/24/
Content-Type: application/json
Authorization: Token  cf0f9bafcccf8becbc45a87da9a3005157becf2b

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=1
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_after=2022-04-23+14:00&created_at_before=2022-04-23+18:00
Content-Type: application/json


###
# фильтрация по статусу
GET {{baseUrl}}/advertisements/?status=OPEN
Content-Type: application/json

