# примеры API-запросов



# получение датчиков
GET http://127.0.0.1:8000/api/sensors/
Content-Type: application/json

###

# создание датчика
POST http://127.0.0.1:8000/api/sensors/
Content-Type: application/json

{
  "name": "ESP34",
  "description": "Датчик на балконе"
}

###

# обновление датчика
PATCH http://127.0.0.1:8000/api/sensors/2/
Content-Type: application/json

{
  "description": "Перенес датчик на балкон"
}

###

# добавление измерения
POST http://127.0.0.1:8000/api/measurements/
Content-Type: application/json

{

  "sensor": 3,
  "temperature": 22

}

###
#
GET http://127.0.0.1:8000/api/measurements/
Content-Type: application/json

###
# получение информации по датчику
GET http://127.0.0.1:8000/api/sensors/2/
Content-Type: application/json
