# Generated by Django 4.0.3 on 2022-03-31 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_tag_articletags_article_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tag',
        ),
        migrations.AddField(
            model_name='articletags',
            name='is_main',
            field=models.CharField(max_length=40, null=True, verbose_name='Главный тег'),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tag', through='articles.ArticleTags', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='articletags',
            name='id_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='articletags',
            name='id_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.tag'),
        ),
    ]
