# Generated by Django 4.0.3 on 2022-03-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_article_tag_articletags_is_main_tag_tag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articletags',
            old_name='id_article',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='articletags',
            old_name='id_tag',
            new_name='tag',
        ),
        migrations.AlterField(
            model_name='articletags',
            name='is_main',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='Главный тег'),
        ),
    ]
